### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by NeerajPise** [xinyooo/deepfake-detection#4]
I noticed that you had mentioned an over-fitting issue in your readme file earlier. I tried the model recently (yesterday) and I'm getting the same issue even after varying data-set size and epochs. I used the Kaggle deep-fake detection challenge data-set and followed the steps mentioned here. Could you tell me whether this model works on your datasets or about anything I might be doing wrong?

**Comment by xinyooo** [comment]
use different datasets such like: https://github.com/ondyari/FaceForensics

**Comment by Aimannnhakim** [comment]
i ve found the solution.. 

detection turns wrong because the format of img array u used for training and the array format u used fr detection seem to be different.

u just have to change line 'data = np.array(img_to_array(cv2.resize(crop_img, (128, 128)))) into 'data=img_to_array(imgresize).flatten() / 255.0' in the model_play

**Comment by xinyooo** [comment]
Thanks for your hard work, this looks great!
